### ISSUE TITLE
Does not work under python < 3.3

### ISSUE THREAD

**Issue by gubenkoved** [windelbouwman/pyspeedscope#1]
Installed successfully on python 2.7, but fails in the runtime due to:

```
Traceback (most recent call last):
  ...
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/speedscope.py", line 17, in track
    recorder.start()
  File "/usr/local/lib/python2.7/dist-packages/speedscope.py", line 34, in start
    self._begin_time = self.get_nanos()
  File "/usr/local/lib/python2.7/dist-packages/speedscope.py", line 31, in get_nanos
    return int(time.perf_counter() * 1e9)
AttributeError: 'module' object has no attribute 'perf_counter'
```

There is a dependency on `perf_counter` from `time` that was only introduced in Python 3.3. As a solution, it should be possible to fall back to a lower resolution timer when `perf_counter` is not available.

https://docs.python.org/3/library/time.html#time.perf_counter

**Comment by windelbouwman** [comment]
Thanks for testing on python2! I did not think too hard about python 2 support. Doe you mean python2 by < 3.3? Or also python3.2 and python3.1?

I'm uncertain whether or not this package (or code snippet), should support python2. The supported python versions should at least be listed in the readme.

Is your opinion that python2 should be supported as well?
